# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lerd < Formula
  desc "Local Laravel development environment for Linux and macOS"
  homepage "https://github.com/geodro/lerd"
  version "1.9.1-beta.1"
  license "MIT"

  depends_on "podman"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/geodro/lerd/releases/download/v1.9.1-beta.1/lerd_1.9.1-beta.1_darwin_amd64.tar.gz"
    sha256 "020824f475de4c082875ae30a00a783b0122e292881e1c7a95f820d785b1e301"

    define_method(:install) do
      bin.install "lerd"
      bin.install "lerd-tray" if File.exist?("lerd-tray")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/geodro/lerd/releases/download/v1.9.1-beta.1/lerd_1.9.1-beta.1_darwin_arm64.tar.gz"
    sha256 "9065b1953d54e7872de1ca4bdf84ec1a2d4c34dc2a94fd37c567092194f807dc"

    define_method(:install) do
      bin.install "lerd"
      bin.install "lerd-tray" if File.exist?("lerd-tray")
    end
  end

  def caveats
    <<~EOS
      To finish setting up Lerd, run:
        lerd install

      To uninstall cleanly, run in order:
        lerd uninstall
        brew uninstall lerd

      If you already removed the binary before running `lerd uninstall`, run:
        ~/.local/bin/lerd-cleanup
        brew uninstall lerd
    EOS
  end
end
