# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lerd < Formula
  desc "Local Laravel development environment for Linux and macOS"
  homepage "https://github.com/geodro/lerd"
  version "1.12.4"
  license "MIT"

  depends_on "podman"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/geodro/lerd/releases/download/v1.12.4/lerd_1.12.4_darwin_amd64.tar.gz"
    sha256 "30a03c889b2e69961119574e009e6b5aaa1a8b92b0b8ef1b3ea03c80318ee713"

    define_method(:install) do
      bin.install "lerd"
      bin.install "lerd-tray" if File.exist?("lerd-tray")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/geodro/lerd/releases/download/v1.12.4/lerd_1.12.4_darwin_arm64.tar.gz"
    sha256 "88da387fdd765dbeaee0e92863a541a4adeedc5bab184af12f2c0a2a5d584d81"

    define_method(:install) do
      bin.install "lerd"
      bin.install "lerd-tray" if File.exist?("lerd-tray")
    end
  end

  def caveats
    <<~EOS
      To finish setting up Lerd, run:
        lerd install

      To uninstall cleanly, run in order:
        lerd uninstall
        brew uninstall lerd

      If you already removed the binary before running `lerd uninstall`, run:
        ~/.local/bin/lerd-cleanup
        brew uninstall lerd
    EOS
  end
end
