# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lerd < Formula
  desc "Local Laravel development environment for macOS"
  homepage "https://github.com/geodro/lerd"
  version "1.2.0-alpha.5"
  license "MIT"

  depends_on "podman"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/geodro/lerd/releases/download/v1.2.0-alpha.5/lerd_1.2.0-alpha.5_darwin_amd64.tar.gz"
    sha256 "d69889419105ef75fbbecd9cd73324054756896743e1114cccfdd755ef232d84"

    define_method(:install) do
      bin.install "lerd"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/geodro/lerd/releases/download/v1.2.0-alpha.5/lerd_1.2.0-alpha.5_darwin_arm64.tar.gz"
    sha256 "f4be968760a5912969748d36862ebe7c27436bfec7d4377d62a943e69d0b7f89"

    define_method(:install) do
      bin.install "lerd"
    end
  end

  def caveats
    <<~EOS
      Run `lerd install` to complete Lerd setup.

      To uninstall cleanly, run `lerd uninstall` before `brew uninstall lerd`.
      If you already removed the binary, run `~/.local/bin/lerd-cleanup` instead.
    EOS
  end
end
